options:
  port:
    type: int
    default: 0
    description: "Papertrail syslog port"
  monitorall:
    type: boolean
    default: false
    description: "Tail and ship all files in /var/log"
  applicationlogs:
    type: string
    default: ""
    description: "Space seperated list of paths to application logs"