options:
  syslog_endpoint:
    type: string
    default: null
    description: "Papertrail syslog endpoint"
  monitorall:
    type: boolean
    default: false
    description: "Tail and ship all files in /var/log"
  applicationlogs:
    type: string
    default: null
    description: "Space separated list of paths to application logs"
