options:
  syslogendpoint:
    type: string
    default: ""
    description: "Papertrail syslog endpoint"
  monitorall:
    type: boolean
    default: false
    description: "Depreciated Config Flag - Does nothing"
  applicationlogs:
    type: string
    default: ""
    description: "Space separated list of paths to application logs"
